# Generated by Django 4.1.11 on 2023-11-02 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='post',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='milestone',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(related_name='tasks', to='gestion.teammember'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.project'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_in_project',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicaldocument',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.project'),
        ),
        migrations.AddField(
            model_name='technicaldocument',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.task'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
